version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: "yarn dev"
    networks:
      - todo-app-2
    depends_on:
      - dev-postgres

  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    networks:
      - todo-app-2
    
networks:
  todo-app-2:
